query GetPaginatedSubmittedProjects(
  $filters: ProjectFilters!
  $pagination: Pagination!
) {
  getPaginatedSubmittedProjects(filters: $filters, pagination: $pagination) {
    skip
    items {
      uuid
      slug
      emoji
      name
      tagline
      description
      howItsMade
      sourceCodeUrl
      url
      event {
        name
      }
      logo {
        file {
          fullUrl
        }
      }
      banner {
        file {
          fullUrl
        }
      }
      screenshots {
        rank
        file {
          fullUrl
        }
      }
      video {
        file {
          fullUrl
        }
        muxUrl
        muxThumbnailUrl
        youtubeId
      }
      primaryRepository {
        url
      }
      prizes {
        name
        poolPrize
        prize {
          name
          emoji
          type
          sponsor {
            name
            organization {
              name
              squareLogo {
                fullUrl
              }
            }
          }
        }
      }
    }
  }
}
