query GetPaginatedSubmittedProjects(
  $filters: ProjectFilters!
  $pagination: Pagination!
) {
  getPaginatedSubmittedProjects(filters: $filters, pagination: $pagination) {
    skip
    items {
      uuid
      logo {
        file {
          fullUrl
        }
      }
      banner {
        file {
          fullUrl
        }
      }
      screenshots {
        rank
        file {
          fullUrl
        }
      }
      video {
        file {
          fullUrl
        }
      }
      prizes {
        prize {
          sponsor {
            organization {
              squareLogo {
                fullUrl
              }
            }
          }
        }
      }
    }
  }
}
